const urbuddyLocators = {
    usernameField: "#userEmail",
    passwordField: "#userPassword",
    loginButton: "[type='submit']",
    firstName: "css=[name='firstName']",
    lastName: "css=[name='lastName']",
    employeeID: "css=[name='id']",
    email: "css=[name='email']",
    role: "css=[name='role']",
    password: "css=[name='password']",
    dob: "css=[name='dob']",
    joiningDate: "css=[name='joiningDate']",
    qualifications: "css=[name='qualifications']",
    department: "css=[name='department']",
    gender: "css=[name='gender']",
    mobileNumber: "css=[name='mobileNumber']",
    bloodGroup: "css=[name='bloodGroup']",
    designation: "css=[name='designation']",
    salary: "css=[name='salary']",
    location: "css=[name='location']",
    reportingTo: "css=[name='reportingTo']",
    addButton: "css=[type='submit']",
    profile: "css=profile-icon-container",
    notification: "css=.notification-container",
    dashboardText: "Dashboard",
    upcomingBirthdayText: "upcoming Birthday",
    upcomingEventText: "upcoming Events",
    upcomingHolidayText: "upcoming Holidays",
    urbuddiCompanyLogo: "companylogo",
    employeesMenu: "[href*='employees']",
    addEmployeeLink: "Add Employee"
};

export default urbuddyLocators;
